### ISSUE TITLE
Debugger for Chrome not able to install in VS code

### ISSUE THREAD

**Issue by devendran1** [microsoft/vscode-chrome-debug#1045]
I have try to update Debugger for Chrome V4.12.10, but it is not installing in VS code

>code --install-extension msjsdiag.debugger-for-chrome
Installing extensions...
Installing extension 'msjsdiag.debugger-for-chrome' v4.12.10...
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:170:17)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at AssertByteCountStream.onerror (_stream_readable.js:744:7)
    at AssertByteCountStream.emit (events.js:203:13)
    at Immediate.<anonymous> (C:\Users\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\yauzl\index.js:558:46)
    at processImmediate (internal/timers.js:439:21) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}

**Comment by roblourens** [comment]
Can you install other extensions?

**Comment by connor4312** [comment]
Closing after after no response
