### ISSUE TITLE
Chrome window crashes

### ISSUE THREAD

**Issue by Skuriles** [microsoft/vscode-chrome-debug#1047]
Hello,

since today I have the following problem:
I start my Angular app with npm start script. Afterwards I start debugging in Chrome by pressing F5. New Chrome window appears and login screen of my app is shown. 
But as soon as I login the Chrome windows crashes instantly (no error message, just closed and gone). 
I tracked it down that it crashes the moment when Signalr connection is established. 
Don't know if it was an update for VS Code or the extension. 

Console Output:
`ERR TreeError [CallStackView] Data tree node not found: [object Object]: Error: TreeError [CallStackView] Data tree node not found: [object Object]
    at z.getDataNode (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1134:302)
    at z.rerender (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1131:979)
    at file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6674:222
    at c.fire (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at N.setName (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6764:35)
    at u.$setDebugSessionName (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4258:791)
    at p._doInvokeHandler (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4346:599)
    at p._invokeHandler (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4346:291)
    at p._receiveRequest (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4344:953)
    at p._receiveOneMessage (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4343:754)
    at file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4341:914
    at c.fire (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at fire (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:434:97)
    at t.PersistentProtocol._receiveMessage (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:438:545)
    at file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:435:635
    at c.fire (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at g.acceptChunk (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:431:445)
    at file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:430:796
    at Socket.t (file:///C:/Users/MYUSERNAME/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:440:185)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
localProcessExtensionHost.ts:233 Extension Host
localProcessExtensionHost.ts:234 FEHLER: Der Prozess "10084" wurde nicht gefunden.
`
The last entry "process not found" always differs in process name. 
Any idea how to solve that. Code has not changed since the last time it worked. So I have no clue what has happend

**Comment by Skuriles** [comment]
Tried it with VS Insiders latest version, still the same problem. VS Code Version is 1.48.2

**Comment by ghous92** [comment]
@Skuriles  - I am also facing the same issue .. looking for some fix all day

**Comment by robste11159** [comment]
I have this issue too. The Chrome Debugger extension for vscode states this:

Important note: By default, this extension now delegates to the new js-debug extension which is built-in to VS Code. Please file issues on that repo. To revert to the old behavior, you can set "debug.javascript.usePreview": false in your settings.

Once I turned off this feature, chrome no longer crashes when I log into my app

**Comment by Skuriles** [comment]
[Here you will find the reasion](https://github.com/microsoft/vscode-js-debug/issues/729)

Seems to be a Chrome issue, not a VS Code/Extension issue.
"debug.javascript.usePreview": false for now should fix it temporary
