### ISSUE TITLE
[webkit-debug-adapter] Path must be a string. (see also #117)

### ISSUE THREAD

**Issue by maxhor** [Microsoft/vscode-chrome-debug#121]
I am facing the same issue as hansrwindhoff in #117. Issue #117 was closed: the "webRoot":  attribute must be changed to "${workspaceRoot}",( instead of ".") I applied those settings.

Help would be very welcome. 

I tried invoking via 'launch with file', 'launch with url' and 'attach'. 

**my npm list**

```
PS H:\vscode\project1> npm list --depth=0
project1@1.0.0 H:\vscode\project1
+-- angular2@2.0.0-beta.8
+-- concurrently@2.0.0
+-- es6-promise@3.1.2
+-- es6-shim@0.33.13
+-- lite-server@2.1.0
+-- reflect-metadata@0.1.2
+-- rxjs@5.0.0-beta.2
+-- systemjs@0.19.6
+-- typescript@1.8.7
`-- zone.js@0.5.15
```

**package.json:**

```
{
  "name": "project1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
	"tsc": "tsc",
	"tsc:w": "tsc -w",
	"lite": "lite-server",
	"app": "concurrent \"npm run tsc:w\" \"npm run lite\" "
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "angular2": "^2.0.0-beta.8",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.33.13",
    "reflect-metadata": "^0.1.2",
    "rxjs": "^5.0.0-beta.2",
    "zone.js": "^0.5.15",
	"systemjs": "0.19.6" 
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0",
	"typescript": "^1.7.5"
  }
}

```

**First invocation: via launch with file, error "path must be a string'**

```
 ›OS: win32 ia32
  ›Node version: v4.1.1
  ›Adapter version: 0.2.2
  ›initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true})
  ›launch({"name":"Launch index.html","type":"chrome","request":"launch","diagnosticLogging":true,"webRoot":"h:\\VSCode\\Project1","file":"index.html"})
  ›TypeError:** Path must be a string**. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at WebKitDebugAdapter.launch (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\webkit\webKitDebugAdapter.js:64:43)
    at C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\adapter\adapterProxy.js:19:76
    at process._tickCallback (node.js:369:9)
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"[webkit-debug-adapter] **Path must be a string**. Received undefined"}
```

**Second invocation via "launch with url. Error: unknown command. And a warning for "can't find page" (can't find page? it's supposed to launch no? )**

```
   ›OS: win32 ia32
  ›Node version: v4.1.1
  ›Adapter version: 0.2.2
  ›initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true})
  ›launch({"name":"Launch localhost with sourcemaps","type":"chrome","request":"launch","diagnosticLogging":true,"url":"http://localhost/testpage.html","webRoot":"h:\\VSCode\\Project1","sourceMaps":true})
  ›spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://localhost/testpage.html"])
  ›Attempting to attach on port 9222
  ›Warning: **Can't find a page with url: http://localhost/testpage.html.** Available pages: ["https://github.com/Microsoft/vscode-chrome-debug/issues/new","http://localhost:9222/","https://github.com/Microsoft/vscode-chrome-debug/issues/117","http://stackoverflow.com/questions/10298859/zend-framework-2-unable-to-render-template-resolver-could-not-resolve-to-a-fil","http://localhost:9222/"]
  ›Warning: Found more than one valid target page. Attaching to the first one. Available pages: ["https://github.com/Microsoft/vscode-chrome-debug/issues/new","http://localhost:9222/","https://github.com/Microsoft/vscode-chrome-debug/issues/117","http://stackoverflow.com/questions/10298859/zend-framework-2-unable-to-render-template-resolver-could-not-resolve-to-a-fil","http://localhost:9222/"]
  ›To target: {"id":1,"method":"Debugger.enable"}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"42","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/ext/common.js","startLine":0,"startColumn":0,"endLine":70,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"43","url":"extensions::runtime","startLine":0,"startColumn":0,"endLine":207,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"44","url":"extensions::binding","startLine":0,"startColumn":0,"endLine":528,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"45","url":"extensions::event_bindings","startLine":0,"startColumn":0,"endLine":511,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"46","url":"extensions::uncaught_exception_handler","startLine":0,"startColumn":0,"endLine":111,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"47","url":"extensions::sendRequest","startLine":0,"startColumn":0,"endLine":150,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"48","url":"extensions::lastError","startLine":0,"startColumn":0,"endLine":143,"endColumn":2,"isContentScript":true}}›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"49","url":"extensions::schemaUtils","startLine":0,"startColumn":0,"endLine":160,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"50","url":"extensions::json_schema","startLine":0,"startColumn":0,"endLine":526,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"51","url":"extensions::utils","startLine":0,"startColumn":0,"endLine":175,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"52","url":"extensions::Event","startLine":0,"startColumn":0,"endLine":11,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"53","url":"extensions::messaging","startLine":0,"startColumn":0,"endLine":393,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"54","url":"extensions::messaging_utils","startLine":0,"startColumn":0,"endLine":54,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"55","url":"extensions::Port","startLine":0,"startColumn":0,"endLine":11,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"56","url":"extensions::extension","startLine":0,"startColumn":0,"endLine":112,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"57","url":"extensions::i18n","startLine":0,"startColumn":0,"endLine":50,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"58","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/ext/content.js","startLine":0,"startColumn":0,"endLine":34,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"59","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/cssProperties.js","startLine":0,"startColumn":0,"endLine":129,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"60","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js","startLine":0,"startColumn":0,"endLine":546,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"61","url":"extensions::messaging","startLine":0,"startColumn":0,"endLine":393,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"62","url":"extensions::event_bindings","startLine":0,"startColumn":0,"endLine":511,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"63","url":"extensions::uncaught_exception_handler","startLine":0,"startColumn":0,"endLine":111,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"64","url":"extensions::sendRequest","startLine":0,"startColumn":0,"endLine":150,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"65","url":"extensions::lastError","startLine":0,"startColumn":0,"endLine":143,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"66","url":"extensions::schemaUtils","startLine":0,"startColumn":0,"endLine":160,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"67","url":"extensions::json_schema","startLine":0,"startColumn":0,"endLine":526,"endColumn":2}}  
›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"68","url":"extensions::utils","startLine":0,"startColumn":0,"endLine":175,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"69","url":"extensions::Event","startLine":0,"startColumn":0,"endLine":11,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"70","url":"extensions::messaging_utils","startLine":0,"startColumn":0,"endLine":54,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"71","url":"extensions::Port","startLine":0,"startColumn":0,"endLine":11,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"72","url":"https://assets-cdn.github.com/assets/frameworks-e677f2022a5d36e8f5ad35d0fcb01f83f1cdb613eda0449f533197693bcc6bda.js","startLine":0,"startColumn":0,"endLine":7,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: could not resolve https://assets-cdn.github.com/assets/frameworks-e677f2022a5d36e8f5ad35d0fcb01f83f1cdb613eda0449f533197693bcc6bda.js to a file in the workspace. webRoot: h:\VSCode\Project1
  ›SourceMaps.scriptParsed: Resolving pending breakpoints for https://assets-cdn.github.com/assets/frameworks-e677f2022a5d36e8f5ad35d0fcb01f83f1cdb613eda0449f533197693bcc6bda.js
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"73","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js","startLine":0,"startColumn":0,"endLine":559,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"74","url":"https://assets-cdn.github.com/assets/github-2294152c3b0a63083bf2fb5d4cd4242f741f0240f42d9be0d37d0c26d448a0b4.js","startLine":0,"startColumn":0,"endLine":13,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: could not resolve https://assets-cdn.github.com/assets/github-2294152c3b0a63083bf2fb5d4cd4242f741f0240f42d9be0d37d0c26d448a0b4.js to a file in the workspace. webRoot: h:\VSCode\Project1
  ›SourceMaps.scriptParsed: Resolving pending breakpoints for https://assets-cdn.github.com/assets/github-2294152c3b0a63083bf2fb5d4cd4242f741f0240f42d9be0d37d0c26d448a0b4.js
  ›From target: {"id":1,"result":{}}
  ›To target: {"id":2,"method":"Console.enable"}
  ›From target: {"id":2,"result":{}}
  ›To client: {"seq":0,"type":"event","event":"initialized"}
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
  ›From client: setFunctionBreakpoints({"breakpoints":[]})
  ›Error: unknowncommand
    at Object.errP (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\webkit\utilities.js:331:13)
    at AdapterProxy.dispatchRequest (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\adapter\adapterProxy.js:16:26)
    at WebKitDebugSession.dispatchRequest (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\webkit\webKitDebugSession.js:88:74)
    at WebKitDebugSession.V8Protocol._dispatch (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\common\v8Protocol.js:200:22)
    at WebKitDebugSession.V8Protocol._handleData (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\common\v8Protocol.js:177:26)
    at Socket.<anonymous> (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\common\v8Protocol.js:59:60)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"setFunctionBreakpoints","success":false,"message":"[webkit-debug-adapter] unknowncommand"}

```

**Third invocation: via "launch". I first opened a page "http://localhost:9222" in chrome. ( error: Not allowed to load local resource: chrome://extension-icon/cfhdojbkjhnklbpkdaibdccddilifddb/24/1)**

 ```
›OS: win32 ia32
  ›Node version: v4.1.1
  ›Adapter version: 0.2.2
  ›initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true})
  ›attach({"name":"Attach","type":"chrome","request":"attach","diagnosticLogging":true,"webRoot":"h:\\VSCode\\Project1","port":9222})
  ›Attempting to attach on port 9222
  ›Warning: Found more than one valid target page. Attaching to the first one. Available pages: ["https://github.com/Microsoft/vscode-chrome-debug/issues/new","http://localhost:9222/","https://github.com/Microsoft/vscode-chrome-debug/issues/117","http://stackoverflow.com/questions/10298859/zend-framework-2-unable-to-render-template-resolver-could-not-resolve-to-a-fil","http://localhost:9222/"]
  ›To target: {"id":1,"method":"Debugger.enable"}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"42","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/ext/common.js","startLine":0,"startColumn":0,"endLine":70,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"43","url":"extensions::runtime","startLine":0,"startColumn":0,"endLine":207,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"44","url":"extensions::binding","startLine":0,"startColumn":0,"endLine":528,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"45","url":"extensions::event_bindings","startLine":0,"startColumn":0,"endLine":511,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"46","url":"extensions::uncaught_exception_handler","startLine":0,"startColumn":0,"endLine":111,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"47","url":"extensions::sendRequest","startLine":0,"startColumn":0,"endLine":150,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"48","url":"extensions::lastError","startLine":0,"startColumn":0,"endLine":143,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"49","url":"extensions::schemaUtils","startLine":0,"startColumn":0,"endLine":160,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"50","url":"extensions::json_schema","startLine":0,"startColumn":0,"endLine":526,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"51","url":"extensions::utils","startLine":0,"startColumn":0,"endLine":175,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"52","url":"extensions::Event","startLine":0,"startColumn":0,"endLine":11,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"53","url":"extensions::messaging","startLine":0,"startColumn":0,"endLine":393,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"54","url":"extensions::messaging_utils","startLine":0,"startColumn":0,"endLine":54,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"55","url":"extensions::Port","startLine":0,"startColumn":0,"endLine":11,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"56","url":"extensions::extension","startLine":0,"startColumn":0,"endLine":112,"endColumn":2,"isContentScript":true}}  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"57","url":"extensions::i18n","startLine":0,"startColumn":0,"endLine":50,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"58","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/ext/content.js","startLine":0,"startColumn":0,"endLine":34,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"59","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/cssProperties.js","startLine":0,"startColumn":0,"endLine":129,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"60","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js","startLine":0,"startColumn":0,"endLine":546,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"61","url":"extensions::messaging","startLine":0,"startColumn":0,"endLine":393,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"62","url":"extensions::event_bindings","startLine":0,"startColumn":0,"endLine":511,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"63","url":"extensions::uncaught_exception_handler","startLine":0,"startColumn":0,"endLine":111,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"64","url":"extensions::sendRequest","startLine":0,"startColumn":0,"endLine":150,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"65","url":"extensions::lastError","startLine":0,"startColumn":0,"endLine":143,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"66","url":"extensions::schemaUtils","startLine":0,"startColumn":0,"endLine":160,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"67","url":"extensions::json_schema","startLine":0,"startColumn":0,"endLine":526,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"68","url":"extensions::utils","startLine":0,"startColumn":0,"endLine":175,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"69","url":"extensions::Event","startLine":0,"startColumn":0,"endLine":11,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"70","url":"extensions::messaging_utils","startLine":0,"startColumn":0,"endLine":54,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"71","url":"extensions::Port","startLine":0,"startColumn":0,"endLine":11,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"72","url":"https://assets-cdn.github.com/assets/frameworks-e677f2022a5d36e8f5ad35d0fcb01f83f1cdb613eda0449f533197693bcc6bda.js","startLine":0,"startColumn":0,"endLine":7,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: could not resolve https://assets-cdn.github.com/assets/frameworks-e677f2022a5d36e8f5ad35d0fcb01f83f1cdb613eda0449f533197693bcc6bda.js to a file in the workspace. webRoot: h:\VSCode\Project1
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"73","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js","startLine":0,"startColumn":0,"endLine":559,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"74","url":"https://assets-cdn.github.com/assets/github-2294152c3b0a63083bf2fb5d4cd4242f741f0240f42d9be0d37d0c26d448a0b4.js","startLine":0,"startColumn":0,"endLine":13,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: could not resolve https://assets-cdn.github.com/assets/github-2294152c3b0a63083bf2fb5d4cd4242f741f0240f42d9be0d37d0c26d448a0b4.js to a file in the workspace. webRoot: h:\VSCode\Project1
  ›From target: {"id":1,"result":{}}›To target: {"id":2,"method":"Console.enable"}
  ›From target: {"id":2,"result":{}}
  ›To client: {"seq":0,"type":"event","event":"initialized"}
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":true}
  ›From client: setFunctionBreakpoints({"breakpoints":[]})
  ›Error: unknowncommand
    at Object.errP (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\webkit\utilities.js:331:13)
    at AdapterProxy.dispatchRequest (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\adapter\adapterProxy.js:16:26)
    at WebKitDebugSession.dispatchRequest (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\webkit\webKitDebugSession.js:88:74)
    at WebKitDebugSession.V8Protocol._dispatch (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\common\v8Protocol.js:200:22)
    at WebKitDebugSession.V8Protocol._handleData (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\common\v8Protocol.js:177:26)
    at Socket.<anonymous> (C:\Users\User\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\common\v8Protocol.js:59:60)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"setFunctionBreakpoints","success":false,"message":"[webkit-debug-adapter] unknowncommand"}

```

**Comment by roblourens** [comment]
I think you had the right fix in adding the `workspaceRoot` to your webRoot. For the other issues, sometimes launch doesn't work properly if Chrome is already open - try closing any other instances first. And "attach" will just look for the first available tab in a session with remote debugging enabled, so you may need to close other tabs or keep them in a session that wasn't launched with `--remote-debugging-enabled`. 

Another workaround for the launch config is the `userDataDir` option. You can set this to a temp directory, and it will use this instead of the user profile, which causes it to start a new Chrome instance instead of reusing an existing one. But I think the existing one will need to not have remote debugging enabled.

**Comment by maxhor** [comment]
I did close the other Chrome instances, I forgot to mention.

So **launching** without any other instance of Chrome running give gives:

`TypeError: Path must be a string. Received undefined`

**Attach**: closing Chrome and then opening chrome with "--remote-debugging-port=9222" 
gives endless messages like

```
›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"48","url":"chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/ext/common.js","startLine":0,"startColumn":0,"endLine":70,"endColumn":0,"isContentScript":true,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"49","url":"extensions::runtime","startLine":0,"startColumn":0,"endLine":207,"endColumn":2,"isContentScript":true}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"50","url":"extensions::binding","startLine":0,"startColumn":0,"endLine":528,"endColumn":2,"isContentScript":true}}

›Paths.scriptParsed: could not resolve https://ssl.gstatic.com/chrome/components/doodle-notifier-02.html to a file in the workspace. webRoot: h:\VSCode\Project1
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"68","url":"https://www.google.nl/_/chrome/newtab?espv=2&ie=UTF-8","startLine":0,"startColumn":28570,"endLine":8,"endColumn":2536,"sourceMapURL":""}}
  ›Paths.scriptParsed: could not resolve https://www.google.nl/_/chrome/newtab?espv=2&ie=UTF-8 to a file in the workspace. webRoot: h:\VSCode\Project1
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"71","url":"https://www.google.nl/_/chrome/newtab?espv=2&ie=UTF-8","startLine":10,"startColumn":3177,"endLine":10,"endColumn":3296,"sourceMapURL":""}}

›Paths.scriptParsed: could not resolve https://plus.google.com/u/0/_/notifications/frame?sourceid=243&hl=nl&origin=https%3A%2F%2Fwww.google.nl&uc=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.j_IXZiClaGQ.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo8oEXzFOrMelu-ob5c2rpRXZlbxug to a file in the workspace. webRoot: h:\VSCode\Project1
  ›From target: {"id":1,"result":{}}
  ›To target: {"id":2,"method":"Console.enable"}
  ›From target: {"method":"Console.messageAdded","params":{"message":{"source":"network","level":"error","text":"Failed to load resource: net::ERR_FAILED","timestamp":1457632029.93686,"type":"log","line":0,"column":0,"url":"chrome-search://thumb/https://www.alex.nl/","networkRequestId":"604.35"}}}
Failed to load resource: net::ERR_FAILED (chrome-search://thumb/https://www.alex.nl/)
```

**Opening chrome** without the "--remote-debugging-port=9222" or with just --remote-debugging (so without "-port=9222") gives error:

`›Error: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222`

**Comment by maxhor** [comment]
That did something! 

(When hovering  above this newly added property "cwd', there is a pop up telling me 'DEPRECATED - renamed to webroot', but anyway)

Only now, I get: 

`XMLHttpRequest cannot load file:///H:/VSCode/Project1/boot.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

Is this a Cross Origin Resource problem? Weird, I'd like to understand. 

But any way: in another world, in Microsoft IIS server, in the web.config file, there is a part for cross domain setting. In my IIS  test environment, the web.config in the project root has the following setting for cross domain: 
```
<customHeaders>
           <add name="Access-Control-Allow-Origin" value="*" />
           <add name="Access-Control-Allow-Headers" value="origin, authorization, access-control-allow-origin, accept, access-control-allow-headers,X-Requested-With, Content-Type" />
         </customHeaders>
```

This setting in web.config is for Microsoft IIS webserver. If my problem is cross domain related (which I do not understand): how can I set cross domain for lite-server ?

**Comment by roblourens** [comment]
Hm, what is XHRing that script? My extension doesn't XHR anything, maybe it's failing to resolve the URL to a path, and vscode is XHRing? Any other clues from the log?

**Comment by maxhor** [comment]
So it should not be XHRing in the first place? Thanks. So I did some googling and I found this: 

`http://stackoverflow.com/questions/27742070`

It has something to do with the server. When I enter` npm run lite `on the command line, the browser pops up and the page shows in http://localhost:3000. Angular is invoked. So outside vscode: all nice.

But inside vscode: if I press F5 in vscode, the browser pops up and I see the raw index.html page. The adress in the browser is: `file:///H:/VSCode/Project1/index.html. `So I do not see the page in localhost, webserver has not been involved. Angular is not invoked.

So i guess there is something wrong with invoking the server. Can there be anything wrong in my package.json or launch.json?

**package.json:**

```
{
  "name": "project1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
	"tsc": "tsc",
	"tsc:w": "tsc -w",
	"lite": "lite-server",
	"app": "concurrent \"npm run tsc:w\" \"npm run lite\" "
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "angular2": "^2.0.0-beta.8",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.33.13",
    "reflect-metadata": "^0.1.2",
    "rxjs": "^5.0.0-beta.2",
    "zone.js": "^0.5.15",
	"systemjs": "0.19.6" 
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0",
	"typescript": "^1.7.5"
  }
}
```

**launch.json**
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch index.html",
			"type": "chrome",
			"request": "launch",
            "cwd": "${workspaceRoot}",
            "diagnosticLogging": true,
            "userDataDir": "C://Users/User/niks",
            "webRoot": "${workspaceRoot}",
			"file": "index.html"
		},
		{
			"name": "Launch localhost with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "diagnosticLogging": true,
            "url": "http://localhost/testpage.html",
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true
		},
		{
			"name": "Attach",
			"type": "chrome",
			"request": "attach",
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}",
			"port": 9222
		}
	]
}


```

**Comment by maxhor** [comment]
I cannot exactly tell what the cause for the Cross Origin Resource has been. After a latest refresh of modules the problem is gone.   

And thanks RobLourens
