### ISSUE TITLE
Cannot read property '0' of undefined from consoleHelper

### ISSUE THREAD

**Issue by bradyholt** [Microsoft/vscode-chrome-debug#281]
I'm getting an unhandled error (which crashes the debugging session) from consoleHelper.js:51:27 which appears to be because the output of a console message is not in an expected format.  Here is the trace:

```
color:green [2016-11-08T16:13:40.769Z] APIAdapterV1::Sending request getInitialUserData (440b8ab5-3aea-447b-bf52-a5f30cb05b13)
******** Unhandled error in debug adapter: TypeError: Cannot read property '0' of undefined
    at resolveParams (/Users/bholt/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.1/node_modules/vscode-chrome-debug-core/out/src/chrome/consoleHelper.js:51:27)
    at Object.formatConsoleMessage (/Users/bholt/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.1/node_modules/vscode-chrome-debug-core/out/src/chrome/consoleHelper.js:17:26)
    at ChromeDebugAdapter.onConsoleAPICalled (/Users/bholt/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.1/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:353:50)
    at ChromeDebugAdapter.onMessageAdded (/Users/bholt/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.1/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:371:18)
    at Client.chrome.Console.onMessageAdded.params (/Users/bholt/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.1/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:143:59)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client.processMessage (/Users/bholt/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.1/node_modules/noice-json-rpc/lib/noice-json-rpc.js:64:18)
    at LoggingSocket.Client.socket.on.message (/Users/bholt/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.1/node_modules/noice-json-rpc/lib/noice-json-rpc.js:28:46)
    at emitTwo (events.js:111:20)
```

Running from Chrome itself, I can see it looks like a POST exception coming from jquery is the console output that the adapter is crashing on.

![image](https://cloud.githubusercontent.com/assets/759811/20107072/d60117dc-a59c-11e6-81cc-ac354f7d76dd.png)

**Comment by roblourens** [comment]
This is #276, will be out with a fix soon

**Comment by roblourens** [comment]
Can I ask which version of Chrome you're using?

**Comment by bradyholt** [comment]
Thanks@ Chrome 53.0.2785.101 (64-bit)

**Comment by roblourens** [comment]
Ok. If you upgrade to 54 it should work. ~53 has a different format for this message than the slightly earlier and later ones I tested.

**Comment by bradyholt** [comment]
Yep, upgrading to 54 worked.  Thanks @roblourens
