### ISSUE TITLE
Error processing "scopes": TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by fehrenhuber** [Microsoft/vscode-chrome-debug#283]
**This exception happens if you start chrome with F5 within VS Studio Code, and then close the chrome browser manually.  If you then try to start the browser with F5 again this exception occurs. The error goes away if you restart VS Studio Code** 

_ChromeDebugAdapter V2.2.2 - VS Studio Code (V 1.7.1)_

Error processing "scopes": TypeError: Cannot read property 'map' of undefined
    at ChromeDebugAdapter.scopes (/opt/schedulix/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:691:47)
    at dispatchRequest (/opt/schedulix/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugSession.js:123:68)
    at ProtocolServer._handleData (/opt/schedulix/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.2/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/opt/schedulix/.vscode/extensions/msjsdiag.debugger-for-chrome-2.2.2/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

**Comment by roblourens** [comment]
Probably https://github.com/Microsoft/vscode-chrome-debug-core/issues/124, you're probably hitting an exception in a Chrome extension or something

**Comment by fehrenhuber** [comment]
What do you mean with 'Will fix'? As there is an external influence on program execution, the code should be that bullet proof, to go on inspite of that influence! So why not checking map property for undefined?

**Comment by roblourens** [comment]
Should be bulletproof but isn't, I guess.
