### ISSUE TITLE
Trouble using Extension together with node.js

### ISSUE THREAD

**Issue by apazureck** [Microsoft/vscode-chrome-debug#287]
Dear sirs,

I have following problem, also posted on stackoverflow.com:
http://stackoverflow.com/questions/40616680/debugging-typescript-in-vscode-with-chrome-using-node-js

I am trying to debug my Typescript code in chrome using the debugging extension for vs code. As webserver I am using nodejs (also as VS Code plugin). When I am doing it with firefox, my breakpoints are hit, hence, when I use chrome I get following Error message:

    ******** Unhandled error in debug adapter: TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at Object.resolveMapPath (C:\Users\pazureck\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapUtils.js:106:96)
    at getSourceMapContent (C:\Users\pazureck\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:71:30)
    at Object.getMapForGeneratedPath (C:\Users\pazureck\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:29:30)
    at SourceMaps.processNewSourceMap (C:\Users\pazureck\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMaps.js:63:32)
    at BaseSourceMapTransformer.scriptParsed (C:\Users\pazureck\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:189:37)
    at ChromeDebugAdapter.onScriptParsed (C:\Users\pazureck\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:314:56)
    at Client.chrome.Debugger.onScriptParsed.params (C:\Users\pazureck\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\node_modules\vscode-chrome-debug-core\out\src\chrom[...]

Here is my launch.json:

    {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Firefox index.html (sourcemaps)",
            "type": "firefox",
            "url": "http://localhost:8080/index.html",
            "webRoot": "${workspaceRoot}",
            "request": "launch"
        },
        {
            "name": "Launch Chrome with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "sourceMaps": true,
            "program": "${workspaceRoot}/server.js",
            "cwd": "${workspaceRoot}",
            "outFiles": ["${workspaceRoot}/**/*.js"]
        },
        // Composite Launches *********************************************************************************************************
        {
            "name": "Launch Node.js with FF",
            "type": "composite",
            "configurationNames": [
                "Launch Program", "Launch Firefox index.html (sourcemaps)"
            ],
            "request": "launch"
        },
        {
            "name": "Launch Node.js with Chrome",
            "type": "composite",
            "configurationNames": [
                "Launch Program", "Launch Chrome with sourcemaps"
            ],
            "request": "launch"
        }
    ]
    }

Here is my server.js

    var express = require('express'),
    app = express(),
    compression = require('compression'),
    open = require('open'),
    serveIndex = require('serve-index'),
    port = process.env.PORT || 8080,
    publicPath = '',
    directory = __dirname + publicPath,
    launchUrl = 'http://localhost:' + port + publicPath,
    year = 60 * 60 * 24 * 365 * 1000;
        
    // use compress middleware to gzip content
    app.use(compression());
    
    // set default mime type to xml for ".library" files
    express.static.mime.default_type = "text/xml";
    
    // serve up content directory showing hidden (leading dot) files
    app.use(publicPath, express.static(directory, { maxAge: year, hidden: true }));
    
    // enable directory listing
    app.use("/", serveIndex(__dirname, {'icons': true}));
    app.use(express.static(directory, { 'dotfiles': 'allow' }));
    
    // start server
    app.listen(port);
    
    // launch uri in default browser
    // open(launchUrl);
    
    // log to server console
    console.log("OpenUI5 SDK server running at\n  => " + launchUrl + " \nCTRL + C to shutdown");

It seems I am doing something wrong publishing the mapping files, as Chrome does not seem to find them? I am also getting nothing useful via google concerning the `outFiles` of my node debug config.

Do you have a hint, how to address this problem or why the chrome debug adapter is receiving a null for the path? It is starting and opening the given webroot, but then I get the error message.

This is also coming up on the js console before the error occurs in my case:

    Tue, 15 Nov 2016 20:34:41 GMT send deprecated hidden: use dotfiles: 'allow' instead at node_modules\serve-static\index.js:96:18

Here is the verbose log output:

```
Verbose logs are written to C:\Users\pazureck\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\vscode-chrome-debug.txt
21:57:46, 15.11.2016
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.6.3
debugger-for-chrome: 2.2.1
From client: initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true}}
From client: launch({"name":"Launch Chrome with sourcemaps","type":"chrome","request":"launch","url":"http://localhost:8080/index.html","sourceMaps":true,"webRoot":"c:\\Dev\\LRA5\\LRA5-FrontEnd\\FrontEnd","diagnosticLogging":true})
spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://localhost:8080/index.html"])
Discovering targets via http://127.0.0.1:9222/json
Warning: Found more than one valid target page. Attaching to the first one. Available pages: ["http://localhost:8080/index.html","http://localhost:8080/index.html","http://localhost:8080/index.html"]
Attaching to target: {"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/ae4a9374-0903-4b4a-82a3-103c2bf10b50","id":"ae4a9374-0903-4b4a-82a3-103c2bf10b50","title":"ifm","type":"page","url":"http://localhost:8080/index.html","webSocketDebuggerUrl":"ws://127.0.0.1:9222/devtools/page/ae4a9374-0903-4b4a-82a3-103c2bf10b50"}
WebSocket Url: ws://127.0.0.1:9222/devtools/page/ae4a9374-0903-4b4a-82a3-103c2bf10b50
To target: "{\"id\":1,\"method\":\"Console.enable\"}"
To target: "{\"id\":2,\"method\":\"Debugger.enable\"}"
To target: "{\"id\":3,\"method\":\"Runtime.enable\"}"
To target: "{\"id\":4,\"method\":\"Runtime.runIfWaitingForDebugger\"}"
To target: "{\"id\":5,\"method\":\"Runtime.run\"}"
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"2016-11-15 21:55:37 Device API logging initialized - DEVICE","url":"http://localhost:8080/resources/sap-ui-core.js","line":18,"column":651}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"2016-11-15 21:55:37.867804 registerResourcePath ('', '/resources/') -  sap.ui.ModuleSystem","url":"http://localhost:8080/resources/sap-ui-core.js","line":160,"column":595}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"2016-11-15 21:55:37.868020 registerResourcePath ('ifm/datalink/linerecorder/ams/frontend', './') -  sap.ui.ModuleSystem","url":"http://localhost:8080/resources/sap-ui-core.js","line":160,"column":595}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"2016-11-15 21:55:37.868239 URL prefixes set to: -  sap.ui.ModuleSystem","url":"http://localhost:8080/resources/sap-ui-core.js","line":160,"column":595}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"2016-11-15 21:55:37.868314   (default) : /resources/ -  sap.ui.ModuleSystem","url":"http://localhost:8080/resources/sap-ui-core.js","line":160,"column":595}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"2016-11-15 21:55:37.868379   'ifm/datalink/linerecorder/ams/frontend' : ./ -  sap.ui.ModuleSystem","url":"http://localhost:8080/resources/sap-ui-core.js","line":160,"column":595}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"deferred","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"utils","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"xml","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"odata","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"odatautils","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"handler","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"metadata","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"net","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"json","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"batch","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"store","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"dom","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"indexeddb","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"memory","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"cache","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"source","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","line":8096,"column":13}}}
From target: {"id":1,"result":{}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"30","url":"http://localhost:8080/resources/sap-ui-core.js","startLine":0,"startColumn":0,"endLine":1774,"endColumn":0,"executionContextId":1,"hash":"6EAD281029F2FC241C11BE41667C02657C14F283","executionContextAuxData":{"isDefault":true,"frameId":"744.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
Paths.scriptParsed: resolved http://localhost:8080/resources/sap-ui-core.js to c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\resources\sap-ui-core.js. webRoot: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"31","url":"http://localhost:8080/scripts/odatajs-4.0.0.js","startLine":0,"startColumn":0,"endLine":8108,"endColumn":0,"executionContextId":1,"hash":"596DC542C1C0C715E9BB0FB70E05C22233866F31","executionContextAuxData":{"isDefault":true,"frameId":"16300.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
Paths.scriptParsed: resolved http://localhost:8080/scripts/odatajs-4.0.0.js to c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\scripts\odatajs-4.0.0.js. webRoot: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"32","url":"http://localhost:8080/ifm.datalink.linerecorder.js","startLine":0,"startColumn":0,"endLine":97,"endColumn":53,"executionContextId":1,"hash":"4CAE0CB00808B9771C906E624AED1C636B671505","executionContextAuxData":{"isDefault":true,"frameId":"16300.1"},"isLiveEdit":false,"sourceMapURL":"ifm.datalink.linerecorder.js.map","hasSourceURL":false}}
Paths.scriptParsed: resolved http://localhost:8080/ifm.datalink.linerecorder.js to c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\ifm.datalink.linerecorder.js. webRoot: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd
SourceMaps.getMapForGeneratedPath: Finding SourceMap for c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\ifm.datalink.linerecorder.js by URI: ifm.datalink.linerecorder.js.map and webRoot: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd
SourceMaps.loadSourceMapContents: Reading local sourcemap file from c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\ifm.datalink.linerecorder.js.map
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"34","url":"http://localhost:8080/resources/sap/m/library-preload.js","startLine":0,"startColumn":0,"endLine":6319,"endColumn":0,"executionContextId":1,"hash":"3DB8573245D5C54161E485C5E3F127519DCA37B6","executionContextAuxData":{"isDefault":true,"frameId":"16300.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
Paths.scriptParsed: resolved http://localhost:8080/resources/sap/m/library-preload.js to c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\resources\sap\m\library-preload.js. webRoot: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd
SourceMap: creating for c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\ifm.datalink.linerecorder.js
SourceMap: sourceRoot: 
SourceMap: sources: ["ifm.datalink.linerecorder.ts"]
SourceMap: webRoot: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd
SourceMap: no sourceRoot specified, using script dirname: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"
SourceMaps.scriptParsed: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\ifm.datalink.linerecorder.js was just loaded and has mapped sources: ["c:\\Dev\\LRA5\\LRA5-FrontEnd\\FrontEnd\\ifm.datalink.linerecorder.ts"]
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"35","url":"http://localhost:8080/resources/sap/ui/core/library-preload.js","startLine":0,"startColumn":0,"endLine":3203,"endColumn":0,"executionContextId":1,"hash":"1B1BCBD272B926E25FAE3F5261C99BAC88C61516","executionContextAuxData":{"isDefault":true,"frameId":"744.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
Paths.scriptParsed: resolved http://localhost:8080/resources/sap/ui/core/library-preload.js to c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd\resources\sap\ui\core\library-preload.js. webRoot: c:\Dev\LRA5\LRA5-FrontEnd\FrontEnd
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"36","url":"","startLine":0,"startColumn":0,"endLine":78,"endColumn":37,"executionContextId":1,"hash":"802B7FF1FEE40F27ABEA1F24D4D4DDEA1D642591","executionContextAuxData":{"isDefault":true,"frameId":"744.1"},"isLiveEdit":false,"sourceMapURL":"Component.js.map","hasSourceURL":false}}
```

Thank you for your help and your great plug-in.

Cheers

**Comment by roblourens** [comment]
I suspect I know what it is, thanks for all the details.

**Comment by roblourens** [comment]
I think it's the same as #268, can you update to 2.3.0 and try again? Thanks

**Comment by apazureck** [comment]
Works like charm 👍 

Thank you very much for the quick fix and thank you for the great work on the extension!
