### ISSUE TITLE
Chrome debug adapter crashes when launched

### ISSUE THREAD

**Issue by elgervb** [Microsoft/vscode-chrome-debug#297]
When launching VSCode debugger, it crashes with the following stacktrace:
I just updated to version: 2.3.0

```
******** Unhandled error in debug adapter: TypeError: Cannot read property 'toLowerCase' of undefined
    at SourceMaps.mapToAuthored (/Users/e.vanboxtel/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMaps.js:32:42)
    at BaseSourceMapTransformer.breakpointResolved (/Users/e.vanboxtel/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/vscode-chrome-debug-core/out/src/transformers/baseSourceMapTransformer.js:203:45)
    at ChromeDebugAdapter.onBreakpointResolved (/Users/e.vanboxtel/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:394:36)
    at Client.chrome.Debugger.onBreakpointResolved.params (/Users/e.vanboxtel/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:142:66)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client.processMessage (/Users/e.vanboxtel/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/noice-json-rpc/lib/noice-json-rpc.js:64:18)
    at LoggingSocket.Client.socket.on.message (/Users/e.vanboxtel/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/noice-json-rpc/lib/noice-json-rpc.js:28:46)
    at emitTwo (events.js:111:20)
    at LoggingSocket.emit (events.js:191:7)

```

My launch configuration:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8001",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

**Comment by roblourens** [comment]
Thanks for the report. I will fix this but I'm not exactly sure what the scenario is to get there. Can you post the log from `verboseDiagnosticLogging: true` too? It's written to a file, the path to which will be at the top of the debug console.

**Comment by alxbl** [comment]
Just wanted to chime in: I have the same issue right now. I took the output of `verboseDiagnosticLogging: true`. It's pretty long (around 1500 lines) so I've attached it. I did a rough find/replace to remove identifying information, but it shouldn't have removed anything helpful.

I haven't tried to write a simple(r) app to repro the issue yet, but I may give it a try later if this persists/if this log isn't helpful. Let me know.

Cheers,
Alex

[chrome-debugger-log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/617144/chrome-debugger-log.txt)

**Comment by roblourens** [comment]
Thanks, that was helpful.

**Comment by roblourens** [comment]
Please try it out in 2.3.1

**Comment by alxbl** [comment]
Working great now. Thanks for the fast response! :)
