### ISSUE TITLE
Sourcemaps after reloading with TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by lordgreg** [Microsoft/vscode-chrome-debug#299]
- VSCode Version: 1.7.2 (1.7.2)
- OS Version: MacOS Sierra 10.12.1 (16B2555)

Issue has been also explained on this url: https://forum.ionicframework.com/t/how-to-debug-typescript-in-ionic-2-apps-using-vs-code-and-app-scripts-0-0-46/70023/12?u=lordgreg

**Steps to Reproduce:**

1. `npm install -g ionic`
2. `ionic start cutePuppyPics --v2`
3. `cd cutePuppyPics`
4. add this part (under description) in `package.json`:
```
  "config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"
  }
```
5. start `ionic serve`.
6. Create `launch.json`:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Chrome Launch",
      "diagnosticLogging": true,
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:8100",
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",
      "runtimeArgs": [
        "--disable-web-security",
        "--user-data-dir",
        "--remote-debugging-port=9222"
      ]
    },
    {
      "name": "Chrome Attach",
      "diagnosticLogging": true,
      "type": "chrome",
      "request": "attach",
      "url": "http://localhost:8100",
      "port": 9222,
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",
      "runtimeArgs": [
        "--disable-web-security",
        "--user-data-dir",
        "--remote-debugging-port=9222"
      ]
    },
    {
      "name": "Canary Attach",
      "diagnosticLogging": true,
      "type": "chrome",
      "request": "attach",
      "url": "http://localhost:8100",
      "webRoot": "${workspaceRoot}",
      "port": 9222,
      "sourceMaps": true,
      "runtimeExecutable": "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
      "runtimeArgs": [
        "--disable-web-security",
        "--user-data-dir",
        "--remote-debugging-port=9222"
      ]
    },
    {
      "name": "Canary Launch",
      "diagnosticLogging": true,
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:8100",
      "port": 9222,
      "sourceMaps": true,
      "runtimeExecutable": "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
      "webRoot": "${workspaceRoot}",
      "runtimeArgs": [
        "--disable-web-security",
        "--user-data-dir",
        "--remote-debugging-port=9222"
      ]
    }
  ]
}

```

No matter the option you pick, debugger will work. However, as soon as you change the ts file (add or remove some console.log) ionic watcher will generate new js and map files. As soon as that happens, VSCode Chrome Debugger will trigger:
```
SourceMaps.scriptParsed: http://localhost:8100/build/main.js was just loaded and has mapped sources: ["/Users/gregorpapez/Projects/@Test/cutePuppyPics/webpack/bootstrap 8ac9ace7eebb9e5e78ad","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/@angular/core/index.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/ionic-native/dist/esm/plugins/plugin.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/ionic-angular/util/util.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/ionic-angular/config/config.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/@angular/compiler/src/facade/lang.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/@angular/core/src/facade/lang.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/ionic-angular/util/dom.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/ionic-angular/components/ion.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/ionic-angular/navigation/view-controller.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/@angular/compiler/src/output/output_ast.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/ionic-angular/components/app/app.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/@angular/compiler/src/identifiers.js","/Users/gregorpapez/Projects/@Test/cutePuppyPics/node_modules/@angular/compiler/src/private_import_core.js","/Users/gregorpapez/Projects/@Test/c[...]
******** Unhandled error in debug adapter: TypeError: Cannot read property 'toLowerCase' of undefined
    at SourceMaps.mapToAuthored (/Users/gregorpapez/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMaps.js:32:42)
    at BaseSourceMapTransformer.breakpointResolved (/Users/gregorpapez/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/vscode-chrome-debug-core/out/src/transformers/baseSourceMapTransformer.js:203:45)
    at ChromeDebugAdapter.onBreakpointResolved (/Users/gregorpapez/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:394:36)
    at Client.chrome.Debugger.onBreakpointResolved.params (/Users/gregorpapez/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:142:66)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client.processMessage (/Users/gregorpapez/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/noice-json-rpc/lib/noice-json-rpc.js:64:18)
    at LoggingSocket.Client.socket.on.message (/Users/gregorpapez/.vscode/extensions/msjsdiag.debugger-for-chrome-2.3.0/node_modules/noice-json-rpc/lib/noice-json-rpc.js:28:46)
    at emitTwo (events.js:111:20)
    at LoggingSocket.emit (events.js:191:7)

``` 

Is there something I'm missing here?

**Comment by roblourens** [comment]
Can you post the verbose log (from the path at the top of the debug console) - it seems like chrome is sending a weird message.

**Comment by lordgreg** [comment]
Hi and thank you for your swift response. Sadly I cannot reproduce the issue on Windows OS. I'll try to ask co-worker to reproduce the issue on Mac OS. If not, the ticket can be set to closed until I get back to work in 2 weeks. 

I'm sorry. :/
