### ISSUE TITLE
Unable to "restart" after I change my page file.

### ISSUE THREAD

**Issue by M0gician** [Microsoft/vscode-chrome-debug#484]
- VS Code Version: 1.15.1
OS: Windows 10 Pro Build 1703, 15063.540

Steps to reproduce:

1. Open any html files
2. Run with "Debugger for chrome" and press "restart".

Info: [debugger-for-chrome] Error processing "restart": TypeError: Cannot read property 'Page' of undefined

What I got in "vscode-chrome-debug":

OS: win32 x64
Adapter node: v7.4.0 x64
vscode-chrome-debug-core: 3.16.5
9:26:56 AM, 8/26/2017
debugger-for-chrome: 3.1.8
From client: 
```
initialize({"clientID":"vscode","adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsRestartRequest":true}}
From client: launch({"type":"chrome","request":"launch","name":"Launch Chrome against localhost","url":"http://localhost:8080","webRoot":"c:\\inetpub\\wwwroot\\TO-Test","trace":true,"noDebug":true,"__sessionId":"bddb7c1a-559d-4a05-a976-649b1bedb22f"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"request":"launch","args":["type","request","name","url","webRoot","trace","noDebug","__sessionId","sourceMaps","sourceMapPathOverrides","skipFileRegExps"]}}}
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
[chromeSpawnHelper] spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--no-first-run","--no-default-browser-check","--user-data-dir=C:\\Users\\Tommy\\AppData\\Local\\Temp\\vscode-chrome-debug-userdatadir_9222","http://localhost:8080"])

got chrome PID: 12740
From client: restart(undefined)
[Error] Error processing "restart": TypeError: Cannot read property 'Page' of undefined
    at ChromeDebugAdapter.restart (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\out\bundle.js:310:27)
    at Object.dispatchRequest (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:75:82)
    at Object.ProtocolServer._handleData (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
To client: {"seq":0,"type":"response","request_seq":3,"command":"restart","success":false,"message":"[debugger-for-chrome] Error processing \"restart\": TypeError: Cannot read property 'Page' of undefined\n    at ChromeDebugAdapter.restart (C:\\Users\\Tommy\\.vscode\\extensions\\msjsdiag.debugger-for-chrome-3.1.8\\out\\bundle.js:310:27)\n    at Object.dispatchRequest (C:\\Users\\Tommy\\.vscode\\extensions\\msjsdiag.debugger-for-chrome-3.1.8\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugSession.js:75:82)\n    at Object.ProtocolServer._handleData (C:\\Users\\Tommy\\.vscode\\extensions\\msjsdiag.debugger-for-chrome-3.1.8\\node_modules\\vscode-debugadapter\\lib\\protocol.js:104:38)\n    at Socket.<anonymous> (C:\\Users\\Tommy\\.vscode\\extensions\\msjsdiag.debugger-for-chrome-3.1.8\\node_modules\\vscode-debugadapter\\lib\\protocol.js:24:60)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread (net.js:551:20)","body":{"error":{"id":1104,"format":"[{_extensionName}] Error processing \"{_requestType}\": {_stack}","variables":{"_extensionName":"debugger-for-chrome","_requestType":"restart","_stack":"TypeError: Cannot read property 'Page' of undefined\n    at ChromeDebugAdapter.restart (C:\\Users\\Tommy\\.vscode\\extensions\\msjsdiag.debugger-for-chrome-3.1.8\\out\\bundle.js:310:27)\n    at Object.dispatchRequest (C:\\Users\\Tommy\\.vscode\\extensions\\msjsdiag.debugger-for-chrome-3.1.8\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugSession.js:75:82)\n    at Object.ProtocolServer._handleData (C:\\Users\\Tommy\\.vscode\\extensions\\msjsdiag.debugger-for-chrome-3.1.8\\node_modules\\vscode-debugadapter\\lib\\protocol.js:104:38)\n    at Socket.<anonymous> (C:\\Users\\Tommy\\.vscode\\extensions\\msjsdiag.debugger-for-chrome-3.1.8\\node_modules\\vscode-debugadapter\\lib\\protocol.js:24:60)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread (net.js:551:20)"},"sendTelemetry":true}}}
```

**Comment by roblourens** [comment]
This implies that Chrome was disconnected, but I don't know how you got into that state. Can you include the full log file? Thanks.

**Comment by M0gician** [comment]
@roblourens 
'''
keybindingsRegistry.ts:197Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  code-runner.run
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  code-runner.runCustomCommand
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  code-runner.runByLanguage
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  code-runner.stop
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
mime.ts:59Overwriting extension <<.asp>> to now point to mime <<text/x-asp>>
(anonymous) @ mime.ts:59
mainThreadExtensionService.ts:117[C:\Users\Tommy\.vscode\extensions\hollowtree.vue-snippets-0.1.2]: Unknown language in `contributes.snippets.language`. Provided value: pug
t.$localShowMessage @ mainThreadExtensionService.ts:117
4mainThreadExtensionService.ts:119[C:\Users\Tommy\.vscode\extensions\hollowtree.vue-snippets-0.1.2]: The "vm.$scopedSlots"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ mainThreadExtensionService.ts:119
extensionHost.ts:335[Extension Host] vscode-icons is active!
messageService.ts:125[debugger-for-chrome] Error processing "restart": TypeError: Cannot read property 'Page' of undefined
    at ChromeDebugAdapter.restart (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\out\bundle.js:310:27)
    at Object.dispatchRequest (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:75:82)
    at Object.ProtocolServer._handleData (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20): Error: [debugger-for-chrome] Error processing "restart": TypeError: Cannot read property 'Page' of undefined
    at ChromeDebugAdapter.restart (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\out\bundle.js:310:27)
    at Object.dispatchRequest (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:75:82)
    at Object.ProtocolServer._handleData (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\Tommy\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.8\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2197625
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:52942)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:56434)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:57755)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:57272)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2016898
    at _.e.dispatch (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2018249)
    at _.e.handleData (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2017757)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:2016758)
    at emitOne (events.js:96:13)
e.doShow @ messageService.ts:125
'''

**Comment by roblourens** [comment]
When you run with `"trace": true` in your launch config, it will write the full log to a file and print that file path at the top of the debug console. That's the full log I mean, can you upload that file here? Thanks.

**Comment by M0gician** [comment]
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1254118/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
I see, that was the whole log file originally. I thought you had cut out the middle. It looks like it just never actually attached to Chrome in the first place.
