### ISSUE TITLE
How can I filter out chrome-extention debuggers and logs?

### ISSUE THREAD

**Issue by mrdulin** [microsoft/vscode-chrome-debug#540]
- VS Code Version:
1.18.0 

Steps to reproduce:

There are too many chrome-extension logs, and it often breakpoint in chrome-extension, I don't want this.
```bash
SourceMaps.loadSourceMapContents: Could not download sourcemap from chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js.map
TypeError: Cannot read property 'sendMessage' of undefined
contextmenuhlpr.js:24
    at dealWithSelection (chrome-extension://ahmpjcflkgiildlgicmcieglgoilbfdp/contextmenuhlpr.js:24:20)
    at HTMLDocument.<anonymous> (chrome-extension://ahmpjcflkgiildlgicmcieglgoilbfdp/contextmenuhlpr.js:73:9)
TypeError: Cannot read property 'sendMessage' of undefined
contextmenuhlpr.js:24
    at dealWithSelection (chrome-extension://ahmpjcflkgiildlgicmcieglgoilbfdp/contextmenuhlpr.js:24:20)
    at HTMLDocument.<anonymous> (chrome-extension://ahmpjcflkgiildlgicmcieglgoilbfdp/contextmenuhlpr.js:73:9)
TypeError: Cannot read property 'sendMessage' of undefined
contextmenuhlpr.js:24
    at dealWithSelection (chrome-extension://ahmpjcflkgiildlgicmcieglgoilbfdp/contextmenuhlpr.js:24:20)
    at HTMLDocument.<anonymous> (chrome-extension://ahmpjcflkgiildlgicmcieglgoilbfdp/contextmenuhlpr.js:73:9)
TypeError: Cannot read property 'sendMessage' of undefined
contextmenuhlpr.js:24
    at dealWithSelection (chrome-extension://ahmpjcflkgiildlgicmcieglgoilbfdp/contextmenuhlpr.js:24:20)
    at HTMLDocument.<anonymous> (chrome-extension://ahmpjcflkgiildlgicmcieglgoilbfdp/contextmenuhlpr.js:73:9)
```
My chrome has many extensions, when I debug my app, it also debug chrome-extension js file.
I know I can launch a new instance chrome. But I use `attach` mode.
I don't want debug chrome-extension, so how can I filter out? Is there an option for this?

**Comment by auchenberg** [comment]
We show the same console messages as Chrome DevTools, so if you want to get rid of your Chrome extension error, simply disable or fix the errors within the given extension.

**Comment by roblourens** [comment]
This is an error from the adapter

**Comment by connor4312** [comment]
VS Code itself added debug console filtering in the last release
