### ISSUE TITLE
Error when launching Chrome with existing breakpoint that fails to get resolved

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#576]
Error when launching Chrome with existing breakpoint that fails to get resolved

```
Error processing "setBreakpoints": TypeError: Cannot read property 'mappedPath' of undefined
    at BaseSourceMapTransformer.setBreakpoints (/Users/auchenberg/.vscode/extensions/msjsdiag.debugger-for-chrome-4.0.0/node_modules/vscode-chrome-debug-core/out/src/transformers/baseSourceMapTransformer.js:63:23)
    at validateBreakpointsPath.then (/Users/auchenberg/.vscode/extensions/msjsdiag.debugger-for-chrome-4.0.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:892:40)
    at <anonymous>
```
<img width="1552" alt="screen shot 2018-01-05 at 1 19 15 pm" src="https://user-images.githubusercontent.com/173559/34628982-3d3766a6-f21b-11e7-8010-e02cdcfe5b1e.png">

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode-chrome-debug-core/issues/256
