### ISSUE TITLE
'Browser.getVersion' wasn't found embedded Chromium

### ISSUE THREAD

**Issue by timc3** [Microsoft/vscode-chrome-debug#671]
I am getting errors with the following error message `'Browser.getVersion' wasn't found`. This occurs frequently, so I just copied in one of the last messages of the log file.

This occurs when running against embedded Chromium in Adobe products.

- VS Code Version: Version 1.23.1 (1.23.1) d0182c3417d225529c6d5ad24b7572815d0de9ac
- Log file:

```
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"report-start-up-timings","data":{"Versions.De
bugAdapterCore":"5.0.2","Versions.DebugAdapter":"4.4.3","Versions.Target.NoUserAgentReason":"Error while retriving target user agent","exc
eptionMessage":"'Browser.getVersion' wasn't found","exceptionName":"Error","exceptionStack":"Error: 'Browser.getVersion' wasn't found\n
 at Client.processMessage (/Users/tim/.vscode/extensions/msjsdiag.debugger-for-chrome-4.4.3/node_modules/noice-json-rpc/lib/noice-json-rpc
.js:66:36)\n    at LoggingSocket.Client.socket.on (/Users/tim/.vscode/extensions/msjsdiag.debugger-for-chrome-4.4.3/node_modules/noice-jso
n-rpc/lib/noice-json-rpc.js:42:48)\n    at emitOne (events.js:101:20)\n    at LoggingSocket.emit (events.js:191:7)\n    at Receiver._recei
ver.onmessage (/Users/tim/.vscode/extensions/msjsdiag.debugger-for-chrome-4.4.3/node_modules/ws/lib/WebSocket.js:141:47)\n    at Receiver.
dataMessage (/Users/tim/.vscode/extensions/msjsdiag.debugger-for-chrome-4.4.3/node_modules/ws/lib/Receiver.js:389:14)\n    at perMessageDe
flate.decompress (/Users/tim/.vscode/extensions/msjsdiag.debugger-for-chrome-4.4.3/node_modules/ws/lib/Receiver.js:349:40)\n    at _decomp
ress (/Users/tim/.vscode/extensions/msjsdiag.debugger-for-chrome-4.4.3/node_modules/ws/lib/PerMessageDeflate.js:306:9)\n    at _inflate.fl
ush (/Users/tim/.vscode/extensions/msjsdiag.debugger-for-chrome-4.4.3/node_modules/ws/lib/PerMessageDeflate.js:386:7)\n    at afterWrite (
_stream_writable.js:383:3)\n    at onwrite (_stream_writable.js:374:7)","RequestedContentWasDetected":"false","Steps":"[\"BeforeFirstStep\
",\"ClientRequest/initialize\",\"ClientRequest/attach\",\"Attach\",\"Attach.RequestDebuggerTargetsInformation\",\"Attach.ProcessDebuggerTa
rgetsInformation\",\"Attach.AttachToTargetDebuggerWebsocket\",\"Attach.ConfigureDebuggingSession.Internal\",\"Attach.ConfigureDebuggingSes
sion.Target\"]","All":"60771.640119","Request.ClientRequest/setBreakpoints.startTime":"[1527154496497,1527154508064]","Request.ClientReque
st/setBreakpoints.timeTakenInMilliseconds":"[2616.603704,1825.900999]","Request.ClientRequest/setExceptionBreakpoints.startTime":"[1527154
499366]","Request.ClientRequest/setExceptionBreakpoints.timeTakenInMilliseconds":"[1.343517]","Request.ClientRequest/configurationDone.sta
rtTime":"[1527154499373]","Request.ClientRequest/configurationDone.timeTakenInMilliseconds":"[0.889995]","Request.ClientRequest/threads.st
artTime":"[1527154499375]","Request.ClientRequest/threads.timeTakenInMilliseconds":"[0.256906]","BeforeFirstStep":"[11.554184]","WaitingAf
ter.ClientRequest/initialize":"[13.750548]","ClientRequest/initialize":"[2.743156]","ClientRequest/attach":"[3.053376]","Attach":"[0.85079
]","Attach.RequestDebuggerTargetsInformation":"[11.328609]","Attach.ProcessDebuggerTargetsInformation":"[1.044697]","Attach.AttachToTarget
DebuggerWebsocket":"[2.676401]","Attach.ConfigureDebuggingSession.Internal":"[0.570967]","WaitingAfter.NotifyInitialized":"[2615.486133]",
"WaitingAfter.ClientRequest/attach":"[2619.480663]","Attach.ConfigureDebuggingSession.Target":"[60737.269762]","RequestedContentWasNotDete
ctedReason":"shutdown"}}}
```

Steps to reproduce:

I recognise that this is probably a minority problem with not a huge number of developers developing against Adobe products, but maybe a wider problem with embedded Chromium in other products as well.
 
1. Launch with Adobe CC 2018 product with debug mode enabled on a panel. 
2. Configure VS Code Debug with Attach

**Comment by roblourens** [comment]
You see the error in the debug console? What's the exact message, is it different from the one in https://github.com/Microsoft/vscode-chrome-debug/issues/633?
