### ISSUE TITLE
  connect ECONNREFUSED，timeout

### ISSUE THREAD

**Issue by ikarosu** [Microsoft/vscode-chrome-debug#696]
- VS Code Version: 1.24.1
- Log file (set `"trace": true` in launch config):
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2166046/vscode-chrome-debug.txt)
OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 6.3.0
17:51:44, 2018-7-5
debugger-for-chrome: 4.7.0
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"zh-cn"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"所有异常","filter":"all","default":false},{"label":"未捕获的异常","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsRestartRequest":true,"supportsSetExpression":true,"supportsLogPoints":true}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/initialize","data":{"Versions.DebugAdapterCore":"6.3.0","Versions.DebugAdapter":"4.7.0","successful":"true","timeTakenInMilliseconds":"2.17928","requestType":"request"}}}
From client: launch({"type":"chrome","request":"launch","name":"vuejs: chrome","url":"http://localhost","webRoot":"D:\\Vue\\gzlsd_mobile\\yuezi/src","breakOnLoad":true,"sourceMapPathOverrides":{"webpack:///src/*":"${webRoot}/*"},"trace":true,"__sessionId":"9530227c-371b-4981-9186-e2e1dbeee8a7"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"Versions.DebugAdapterCore":"6.3.0","Versions.DebugAdapter":"4.7.0","request":"launch","args":["type","request","name","url","webRoot","breakOnLoad","sourceMapPathOverrides","trace","__sessionId","breakOnLoadStrategy","pathMapping","sourceMaps","skipFileRegExps"]}}}
Discovering targets via http://127.0.0.1:9222/json/list
[chromeSpawnHelper] spawn('C:\Users\q\AppData\Local\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","--user-data-dir=C:\\Users\\q\\AppData\\Local\\Temp\\vscode-chrome-debug-userdatadir_9222","about:blank"])

got chrome PID: 13644
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/launch","data":{"Versions.DebugAdapterCore":"6.3.0","Versions.DebugAdapter":"4.7.0","successful":"false","exceptionType":"firstChance","exceptionMessage":"无法连接到运行中的进程，将在{_timeout}毫秒后超时 - （原因：{_error}）","exceptionName":"Error","exceptionStack":"Error: 无法连接到运行中的进程，将在{_timeout}毫秒后超时 - （原因：{_error}）\n    at Object.runtimeConnectionTimeout (errors.js:91:12)\n    at utils.retryAsync.catch.err (chromeConnection.js:100:49)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:109:7)","exceptionId":"2010","timeTakenInMilliseconds":"10718.527892","requestType":"request"}}}
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"无法连接到运行中的进程，将在10000毫秒后超时 - （原因：无法连接到目标：connect ECONNREFUSED 127.0.0.1:9222）","body":{"error":{"id":2010,"format":"无法连接到运行中的进程，将在{_timeout}毫秒后超时 - （原因：{_error}）","variables":{"_error":"无法连接到目标：connect ECONNREFUSED 127.0.0.1:9222","_timeout":"10000"}}}}
From client: disconnect({"restart":false})

Steps to reproduce:

1.F5 start
2.wait browser open new window is a ablut:blank
3.a minitue later show a window with error

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug#cannot-connect-to-the-target-connect-econnrefused-1270019222
