### ISSUE TITLE
Network.setCacheDisabled

### ISSUE THREAD

**Issue by qkdreyer** [Microsoft/vscode-chrome-debug#754]
- VS Code Version: 1.30.0-insider (dcc243c9920f0077e87e4a7befbc67c713a1709b)
- Log file (set `"trace": true` in launch config): https://pastebin.com/raw/UiWPDSrR

Steps to reproduce:

0. Using debugger configuration :
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "attach",
      "name": "Remote Debug iOS Webkit Adapter",
      "port": 9000,
      "webRoot": "${workspaceFolder}/www",
      "trace": true
    }
  ]
}
```

1. Start remotedebug_ios_webkit_adapter (https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#using-with-microsoft-vs-code)
2. Open a tab using Safari on iOS Device (iPhone X)
3. Debug `Remote Debug iOS Webkit Adapter`

```
Verbose logs are written to:
/var/folders/_g/srx39mls3yb_fb46ck1q0vbm0000gn/T/vscode-chrome-debug.txt
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: 'Network.setCacheDisabled' was not found
    at Client.processMessage (/Users/qkdreyer/.vscode-insiders/extensions/msjsdiag.debugger-for-chrome-4.11.1/node_modules/noice-json-rpc/lib/noice-json-rpc.js:66:36)
    at LoggingSocket.Client.socket.on (/Users/qkdreyer/.vscode-insiders/extensions/msjsdiag.debugger-for-chrome-4.11.1/node_modules/noice-json-rpc/lib/noice-json-rpc.js:42:48)
    at emitOne (events.js:121:20)
    at LoggingSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/Users/qkdreyer/.vscode-insiders/extensions/msjsdiag.debugger-for-chrome-4.11.1/node_modules/ws/lib/websocket.js:719:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (/Users/qkdreyer/.vscode-insiders/extensions/msjsdiag.debugger-for-chrome-4.11.1/node_modules/ws/lib/receiver.js:414:14)
    at perMessageDeflate.decompress (/Users/qkdreyer/.vscode-insiders/extensions/msjsdiag.debugger-for-chrome-4.11.1/node_modules/ws/lib/receiver.js:371:23)
    at _decompress (/Users/qkdreyer/.vscode-insiders/extensions/msjsdiag.debugger-for-chrome-4.11.1/node_modules/ws/lib/permessage-deflate.js:307:9)
```

**Comment by qkdreyer** [comment]
https://github.com/Microsoft/vscode-chrome-debug/blob/831d9365777cc0e80b2966d444fb876ceae09953/src/chromeDebugAdapter.ts#L234

**Comment by auchenberg** [comment]
This is caused by `Network.setCacheDisabled` not being implemented in Webkit. 

@roblourens  Our DA should probably handle these cases better instead of throwing an Unhandled error

**Comment by roblourens** [comment]
This shouldn't break anything but I pushed a change to hide the error.
