### ISSUE TITLE
No URL script source with id: 55 because it already exists and it's associated to a different value

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-chrome-debug#897]
Got this while using chrome-debug with electron

```
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: Cannot set key <eval>\VM55 for value <eval>\VM55: No URL script source with id: 55 because it already exists and it's associated to a different value: <eval>\VM55: No URL script source with id: 55
    at ValidatedMap.setAndIgnoreDuplicates (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/collections/validatedMap.js:91:19)
    at MapUsingProjection.setAndIgnoreDuplicates (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/collections/mapUsingProjection.js:82:39)
    at params.script.allSources.forEach.source (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/internal/sources/sourceResolver.js:33:36)
    at Array.forEach (<anonymous>)
    at SourceResolver._cdtpOnScriptParsedEventProvider.onScriptParsed (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/internal/sources/sourceResolver.js:31:38)
    at _listeners.map.listener (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/communication/listeners.js:1[...]
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: Cannot set key <eval>\VM97 for value <eval>\VM97: No URL script source with id: 97 because it already exists and it's associated to a different value: <eval>\VM97: No URL script source with id: 97
    at ValidatedMap.setAndIgnoreDuplicates (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/collections/validatedMap.js:91:19)
    at MapUsingProjection.setAndIgnoreDuplicates (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/collections/mapUsingProjection.js:82:39)
    at params.script.allSources.forEach.source (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/internal/sources/sourceResolver.js:33:36)
    at Array.forEach (<anonymous>)
    at SourceResolver._cdtpOnScriptParsedEventProvider.onScriptParsed (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/internal/sources/sourceResolver.js:31:38)
    at _listeners.map.listener (/home/roblou/.vscode-server-insiders/extensions/msjsdiag.debugger-for-chrome-nightly-2019.7.26820/node_modules/vscode-chrome-debug-core/out/src/chrome/communication/listeners.js:1[...]
```

[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3433726/vscode-chrome-debug.txt)

**Comment by digeff** [comment]
Fixed in several cases in: https://github.com/microsoft/vscode-chrome-debug-core/pull/496
