### ISSUE TITLE
Launch Chrome task results in message "Cannot connect to runtime process"

### ISSUE THREAD

**Issue by ryanrodemoyer** [microsoft/vscode-chrome-debug#992]
- VS Code Version: 1.42.1
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/4339196/vscode-chrome-debug.txt)
- NodeJS version: 12.16.1
- Windows 10 Version 1903

Log file is attached to the issue.

General Notes:
1. At some point in the past, the Launch Chrome task did work for everyone. I am unsure when exactly this broke but it has been a problem for us over the past several months.
1. I do not know the next avenue to investigate to resolve this issue. My gut tells me that maybe we some have some type of corporate spyware blocking something that makes this launch task fail.
1. I have several dozen developers who are experiencing this issue when trying to launch Chrome to debug our Angular app. We have, in my opinion, exhausted all other known or potential solutions to this problem.
   * Things we tried (non-exhaustive list):
      * Looking for processes using port 9222 (none)
      * Closing all instances of cmd, chrome, and VSCode
      * Restarting VSCode
      * Restarting Windows
1. We can successfully use a Chrome attach task if we manually launch Chrome.exe with the `--remote-debugging-port` flag.
1. A Chrome window never appears after running the launch task.
1. I have tried several combinations of extra parameters via the `launch.json` task. For `address` I have also tried `localhost`.

Steps to reproduce:

1. Run my app via `ng serve`.
2. Run my Chrome launch task. An error appears shortly after with the text `Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222)`.

![image](https://user-images.githubusercontent.com/4162593/76779767-7fb8bc00-6771-11ea-8a0c-ef68c7325b76.png)

**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}",
            "trace": "verbose"
        }
    ]
}
```

**ng serve**
```
PS C:\ryandata\code2\angular\MyBaseDialogProject> ng serve
Your global Angular CLI version (9.0.6) is greater than your local
version (1.4.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2020-03-16T16:27:05.465Z
Hash: de4f0dced9279bdde4e5
Time: 5339ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 38.7 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 200 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.3 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.54 MB [initial] [rendered]

webpack: Compiled successfully.
```

**Comment by roblourens** [comment]
Does it work if you set `"userDataDir": false` in your launch config? Make sure to kill all Chrome windows first in that case.

**Comment by ryanrodemoyer** [comment]
Alrighty, tried this. 

1. The problem persists.
1. I do not see any instance of Chrome appear on my screen.

![image](https://user-images.githubusercontent.com/4162593/77095796-0240b600-69d4-11ea-9054-43eecd697b74.png)

**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}",
            "trace": "verbose",
            "userDataDir": false
        }
    ]
}
```

**Debug Console**
```
Verbose logs are written to:
C:\Users\RYAN~1.ROD\AppData\Local\Temp\vscode-chrome-debug.txt
2020-3-19, 17:19:55.830 UTC
OS: win32 x64
Adapter node: v12.8.1 x64
vscode-chrome-debug-core: 6.8.7
debugger-for-chrome: 4.12.6
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsBreakpointLocationsRequest":false,"supportsRestartRequest":true,"supportsSetExpression":true,"supportsLogPoints":true}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/initialize","data":{"Versions.DebugAdapterCore":"6.8.7","Versions.DebugAdapter":"4.12.6","successful":"true","timeTakenInMilliseconds":"2.829001","requestType":"request"}}}
From client: launch({"type":"chrome","request":"launch","name":"Launch Chrome against localhost","url":"http://localhost:4200","webRoot":"C:\\RyanData\\code2\\angular\\MyBaseDialogProject","trace":"verbose","userDataDir":false,"__sessionId":"9746b472-c3b8-4e6d-b340-152b0dd5ad2c"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"Versions.DebugAdapterCore":"6.8.7","Versions.DebugAdapter":"4.12.6","request":"launch","args":["type","request","name","url","webRoot","trace","userDataDir","__sessionId","breakOnLoadStrategy","pathMapping","sourceMaps","sourceMapPathOverrides","skipFileRegExps","targetFilter","smartStep","showAsyncStacks"]}}}
Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
Discovering targets via http://127.0.0.1:9222/json/list
[chromeSpawnHelper] spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","about:blank"])
got chrome PID: 27952
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
Discovering targets via http://127.0.0.1:9222/json/list
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/launch","data":{"Versions.DebugAdapterCore":"6.8.7","Versions.DebugAdapter":"4.12.6","successful":"false","exceptionType":"firstChance","exceptionMessage":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","exceptionName":"Error","exceptionStack":"Error: Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).\n    at Object.runtimeConnectionTimeout (errors.js:91:12)\n    at chromeConnection.js:110:49\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)","exceptionId":"2010","timeTakenInMilliseconds":"13013.7683","requestType":"request"}}}
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).","body":{"error":{"id":2010,"format":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222","_timeout":"10000"}}}}
```

**Comment by roblourens** [comment]
Hm, and is `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` the right location of Chrome?

You might want to try this with our new debugger implementation too that fixes a lot of issues.
https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by ryanrodemoyer** [comment]
First, I had some success with the preview Javascript Debugger.

Good. Chrome launched via VS Code!
Bad. There's an issue loading symbols and the pages in our app never load. In other words, Chrome launches and navigates to the URL but then sits while spinning and nothing ever really happens. I had to F12 for the browser dev tools and there was something going on with loading symbols. The breakpoints in my app failed to load. Also, I was not able to attach to the app and hit breakpoints. Perhaps I can try a screen recording when I have a bit of time this week to get back to it.

Second, confirmed that's the location of Chrome on my machine. One of the first things I checked early in this debugging process ; )

**Comment by roblourens** [comment]
Hm, that's interesting since there shouldn't really be an important difference in the way Chrome is launched. But, the preview debugger is the future so I'm glad it works there.

> Chrome launches and navigates to the URL but then sits while spinning and nothing ever really happens

We just navigate to whatever URL you give, and if the page doesn't load, there must be an issue with the server/page. I'm not sure what you are referring to by "symbols" here.
